use_frameworks!

target 'KImageCropper_Example' do
  pod 'KImageCropper', :path => '/Users/sagar/Desktop/Pod Folder/KImageCropper'

  target 'KImageCropper_Tests' do
    inherit! :search_paths

    
  end
end
